{{- if .Values.global.smtpCreateSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
  namespace: {{ .Release.Namespace }}
  labels: {{- include "platform-service.labels" . | nindent 4 }}
  annotations: {}
type: Opaque
data:
{{- include "platform-service.generateSmtpSecrets" . }}
{{- end }}