apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: {{.Values.namespace}}
  labels:
    app: postgres
    created_by: {{.Values.created_by | replace "@" "-"}}
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgres
        created_by: {{.Values.created_by | replace "@" "-"}}
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      nodeSelector:
        cloud.google.com/gke-preemptible: "true"
      tolerations:
        - effect: NoSchedule
          key: cloud.google.com/gke-preemptible
          value: "true"
          operator: Equal
      containers:
        - name: postgres
          image: postgres:14.4
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              value: {{.Values.password}}
            - name: PGDATA
              value: /data/pgdata
          livenessProbe:
            exec:
              command: [psql, 'postgres://postgres:espresso@localhost:5432/?sslmode=disable', '-c', ';']
            initialDelaySeconds: 15
          resources:
            limits:
              cpu: {{.Values.resources.cpu}}
              memory: {{.Values.resources.memory}}
            requests:
              cpu: {{.Values.resources.cpu}}
              memory: {{.Values.resources.memory}}
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - mountPath: /data
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{.Values.storage}}