global:
  loadbalancerURL: ""
  imagePullSecrets: []
  ingress:
    useSelfSignedCert: false
namespace: 
  name: <+infra.namespace>
  annotated: false

created_by: <+pipeline.triggeredBy.email>
autoStopConnector: <+pipeline.variables.autoStopConnector>
enableAutoStopping: <+pipeline.variables.enableAutoStopping>

# mongoImage: mongo:4.2.18
# mongoinstallImage: <+artifact.image>
# busyboxImage: busybox:1.29

replicas: 3

cpu: 500m
memory: 1Gi
storageSize: 5Gi
storageClass: standard
wiredTigerCacheSizeGB: 1

mongodbAdminUser: admin
mongodbAdminPassword: admin
keyfile: aGFybmVzcw==
ENV: pr