mongodb:
  architecture: replicaset
  fullnameOverride: "mongodb-replicaset-chart"
  image:
    registry: docker.io
    repository: bitnami/mongodb
    tag: 4.2.19
  replicaCount: 3
  arbiter:
    enabled: true
  service:
    nameOverride: "mongodb-replicaset-chart"
  auth:
    rootUser: "admin"
  podLabels: 
    - name: app
      value: mongodb-replicaset
  resources:
    limits:
      cpu: 4
      memory: 8192Mi
    requests:
      cpu: 4
      memory: 8192Mi
  persistence:
    size: 200Gi
