apiVersion: batch/v1
kind: Job
metadata:
  name: ti-migration-{{ lower ( randAlphaNum 6 ) }}
  namespace: {{ .Release.Namespace }}
  annotations:
  labels:
    {{- include "ti-service.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ti-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: migrate
        image: {{ include "common.images.image" (dict "imageRoot" .Values.jobs.migrate.image "global" .Values.global) }}
        imagePullPolicy: {{ .Values.jobs.migrate.image.pullPolicy}}
        command: ["/bin/bash", "-c", "sleep 300 && /opt/harness/migrate.sh" ]
        resources:
          {{- toYaml .Values.jobresources | nindent 10 }}
        env:
          {{- include "harnesscommon.dbconnection.mongoEnv" . | indent 10 }}
          - name: TI_SERVICE_MONGODB_CONN_STR
            value: {{ include "harnesscommon.dbconnection.mongoConnection" (dict "database" "ti-harness" "context" $) }}
          {{- if .Values.global.database.timescaledb.installed }}
          - name: TI_SERVICE_TIMESCALE_USERNAME
            value: "postgres"
          - name: TI_SERVICE_TIMESCALE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.tiServiceTimescaleSecret.password.name }}
                key: {{ .Values.tiServiceTimescaleSecret.password.key }}
          - name: TI_SERVICE_TIMESCALE_HOST
            value: timescaledb-single-chart.{{ .Release.Namespace }}
          - name: TI_SERVICE_TIMESCALE_PORT
            value: "5432"
          {{- else }}
            {{ include "harnesscommon.dbconnection.dbenvuser" (dict "type" "timescale" "variableName" "TI_SERVICE_TIMESCALE_USERNAME" "secret" .Values.global.database.timescaledb.secretName "userKey" .Values.global.database.timescaledb.userKey ) | nindent 10 }}
            {{ include "harnesscommon.dbconnection.dbenvpassword" (dict "type" "timescale" "variableName" "TI_SERVICE_TIMESCALE_PASSWORD" "secret" .Values.global.database.timescaledb.secretName "passwordKey" .Values.global.database.timescaledb.passwordKey ) | nindent 10 }}
          - name: TI_SERVICE_TIMESCALE_HOST
            value: {{ (split ":" (index .Values.global.database.timescaledb.hosts 0))._0 }}
          - name: TI_SERVICE_TIMESCALE_PORT
            value: {{ (split ":" (index .Values.global.database.timescaledb.hosts 0))._1 | quote }}
          - name: TI_SERVICE_TIMESCALE_ENABLE_SSL
            value: "true"
          - name: TI_SERVICE_TIMESCALE_SSL_MODE
            value: "verify-full"
          - name: TI_SERVICE_TIMESCALE_SSL_CERT_PATH
            value: "/opt/harness/svc/timescale_ca.pem"
          {{- end }}
        {{- if not .Values.global.database.timescaledb.installed }}
        volumeMounts:
          - name: timescaledb-cert
            mountPath: /opt/harness/svc
      volumes:
      - name: timescaledb-cert
        secret:
          secretName: {{ .Values.global.database.timescaledb.certName }}
          items:
          - key: {{ .Values.global.database.timescaledb.certKey }}
            path: timescale_ca.pem
      {{- end }}
      restartPolicy: Never
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" $) | nindent 8 }}
      {{- end }}
