apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: learning-engine
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: "50%"
  selector:
   matchLabels:
    app: learning-engine
