apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pipeline-service.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: "50%"
  selector:
   matchLabels:
    app: pipeline-service
