{{- if and .Values.global.cg.enabled .Values.global.ng.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: migrator
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: "50%"
  selector:
   matchLabels:
    app: migrator
{{- end }}

