{{- if and .Values.global.cg.enabled .Values.global.ng.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "migrator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "migrator.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "migrator.generateSecrets" . }}
{{- end }}
