apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "migrator.labels" . | nindent 4 }}
  name: migrator
  namespace: {{ .Release.Namespace }}
  annotations: {}
spec:
  ports:
    - name: http-manager
      port: {{.Values.service.port}}
      protocol: TCP
      targetPort: {{.Values.service.port}}
    - name: grpc-manager
      port: {{.Values.service.grpcport}}
      protocol: TCP
      targetPort: {{.Values.service.grpcport}}
  selector:
    {{- include "migrator.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: {{.Values.service.type}}
