{{- if .Values.enableAutoStopping}}
apiVersion: ccm.harness.io/v1
kind: AutoStoppingRule
metadata:
    name: mongo-as-rule-{{.Values.namespace.name}}-{{lower .Values.autoStopConnector}}
    namespace: {{.Values.namespace.name}}
    annotations:
        harness.io/cloud-connector-id: {{.Values.autoStopConnector}}
spec:
    idleTimeMins: 30
    workloadName: mongo-replicaset
    workloadType: StatefulSet
{{- end}}
Footer
