apiVersion: v1
kind: Secret
metadata:
  name: {{ include "access-control.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "access-control.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "access-control.generateSecrets" . }}