apiVersion: v1
kind: Service
metadata:
  name:  {{ include "access-control.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "access-control.labels" . | nindent 4 }}
spec:
  type: {{.Values.service.type}}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    {{- include "access-control.selectorLabels" . | nindent 4 }}
