apiVersion: v1
kind: ConfigMap
metadata:
  name: ng-auth-ui
  namespace: {{ .Release.Namespace }}
data:
  DEPLOYMENT_TYPE: ON_PREM
  API_URL: /gateway
  {{- if .Values.additionalConfigs }}
  {{- toYaml .Values.additionalConfigs | nindent 2 }}
  {{- end }}
