{{- if and .Values.secrets .Values.secrets.stores }}
{{- $namespace := .Release.Namespace }}
{{- $useExternal := .Values.global.useExternalSecrets }}
{{- range $store := .Values.secrets.stores }}
{{- $storeName := $store.name }}

{{- if $useExternal }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harness-manger-{{ $storeName }}
  namespace: {{ $namespace }}
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $storeName }}
  target:
    template:
      type: Opaque
      engineVersion: v2
      data: 
        {{- range $k,$v := $store.secrets }}
        {{ $sString := (printf "{{ `{{ .%s }}` }}" ($k | lower))}}
        {{- printf "%s : %s" ($k | upper) $sString  }}
        {{- end }}
    creationPolicy: Owner
  data:
  {{- range $k,$v := $store.secrets }}
    - secretKey: {{ $k | lower}}
      remoteRef:
        key: {{ $k | lower }}
  {{- end }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: harness-manger-{{ $storeName }}
data:
  {{- range $k,$v := $store.secrets}}
  {{ printf "%s: %s" ($k | upper) ($v | quote) }}
  {{- end }}
{{- end }}
{{- end}}
{{- end }}