{{- if and .Values.secrets .Values.secrets.stores }}
{{- $namespace := .Release.Namespace }}
{{- $useExternal := .Values.global.useExternalSecrets }}
{{- $env := .Values.secrets.env }}
{{- range $store := .Values.secrets.stores }}
{{- $storeName := $store.name }}
{{- if $useExternal }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harness-manager-{{ $storeName }}
  namespace: {{ $namespace }}
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $storeName }}
  target:
    name: harness-manager-{{ $storeName }}
    creationPolicy: Owner    
    template:
      type: Opaque
      engineVersion: v2
      data: 
        {{- range $k,$v := $store.secrets }}
        {{- $sString := (printf "{{ .%s  }}" ($k | lower))}}
        {{ printf "%s: \"%s\"" ($k | upper) $sString  }}
        {{- end }}
    creationPolicy: Owner
  data:
  {{- range $k,$v := $store.secrets }}
    - secretKey: {{ $k | lower}}
      remoteRef:
        key: {{ printf "%s_%s" $env ($k | upper) }}
  {{- end }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: harness-manager-{{ $storeName }}
data:
  {{- range $k,$v := $store.secrets}}
  {{ printf "%s: %s" ($k | upper) ($v | quote) }}
  {{- end }}
{{- end }}
---
{{- end}}
{{- end }}
