apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harness-manager.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-manager.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "harness-manager.generateSecrets" . }}