apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "verification-svc.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "verification-svc.selectorLabels" . | nindent 6 }}
