apiVersion: v1
kind: Service
metadata:
  name: verification-svc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "verification-svc.labels" . | nindent 4 }}
spec:
  type: {{.Values.service.type}}
  ports:
  - name: verification
    port: {{.Values.service.port}}
    protocol: TCP
    targetPort: {{.Values.service.port}}
  selector:
     {{- include "verification-svc.selectorLabels" . | nindent 4 }}
