{{ if not .Values.global.disableHarnessSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  annotations: {}
type: Opaque
data:
{{- include "harnesssecrets.generateMinioSecrets" . }}
{{ end }}
